const { DataTypes } = require('sequelize');
const { sequelize } = require('./index');

const SchoolTimeTable = sequelize.define('SchoolTimeTable', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  period_name: { type: DataTypes.STRING(100), allowNull: false },
  period_type: { type: DataTypes.ENUM('class', 'break', 'lunch'), allowNull: false },
  start_time: { type: DataTypes.TIME, allowNull: false },
  duration_minutes: { type: DataTypes.INTEGER, allowNull: false },
  // end_time is generated by the DB (stored generated column); reflect it as a read-only field
  end_time: { type: DataTypes.TIME, allowNull: true },
  is_block: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  block_id: { type: DataTypes.INTEGER, allowNull: true },
  day_of_week: { type: DataTypes.TINYINT, allowNull: false, comment: '1 = Monday, 5 = Friday' }
}, {
  tableName: 'school_time_table',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at'
});

module.exports = SchoolTimeTable;
